---
- name: create deployment structure
  deploy_helper: path="{{ deploy_directory }}" state=present

- name: clone repository
  git: repo="{{ deploy_repository }}" dest="{{ deploy_helper.new_release_path }}" version="{{ deploy_reference }}"

- file: path="{{ deploy_helper.new_release_path }}/{{ deploy_helper.unfinished_filename }}" state=touch

- name: install Python requirements into virtualenv
  pip:
      chdir: "{{ deploy_helper.new_release_path }}"
      requirements: "requirements.txt"
      virtualenv: "{{ deploy_helper.new_release_path }}/env"
      virtualenv_site_packages: yes

